### ISSUE TITLE
Cleanup for v0.1 checklist

### ISSUE THREAD

**Issue by midnightfreddie** [midnightfreddie/McpeTool#10]
- [x] change apiVersion to 1.0
- [x] change CLI version string to 0.1.0
- [x] documentation check

Optional:

- [ ] basic in-browser query/update tool
- [x] sample REST API task scripts
